/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebas;

import javax.swing.JOptionPane;

/**
 *
 * @author Gladys Lopera
 */
public class ModificacionesPresupuestales extends javax.swing.JFrame {

    /**
     * Creates new form ModificacionesPresupuestales
     */
    public ModificacionesPresupuestales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_IdProducto = new javax.swing.JTextField();
        txt_EspecificacionProducto = new javax.swing.JTextField();
        txt_MarcaProducto = new javax.swing.JTextField();
        txt_PrecioNeto = new javax.swing.JTextField();
        btn_cancelar = new javax.swing.JButton();
        txt_UnidadCompra = new javax.swing.JTextField();
        txt_IdUnidadCompra = new javax.swing.JTextField();
        btn_buscarunidadcompra = new javax.swing.JButton();
        txt_NombreProducto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_DescuentoProdEnt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_ImpuestoProdEnt = new javax.swing.JTextField();
        Subtotal = new javax.swing.JLabel();
        txt_SubtotalProdEnt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_buscarproducto = new javax.swing.JButton();
        btn_nuevo1 = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        Subtotal1 = new javax.swing.JLabel();
        cbo_EstadoProDent = new javax.swing.JComboBox<>();
        Subtotal2 = new javax.swing.JLabel();
        txt_ObservacionEstado = new javax.swing.JTextField();
        txt_IdUnidadProducto = new javax.swing.JTextField();
        txt_RelacionUcUp = new javax.swing.JTextField();
        txt_CantEntInventario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_CantidadProducto = new javax.swing.JTextField();
        txt_IdDetalleEntrada = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_UnidadProducto = new javax.swing.JTextField();
        txt_CantSalInventario = new javax.swing.JTextField();
        txt_FechaOrden = new javax.swing.JTextField();
        Jpanel56 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaListado = new javax.swing.JTable();
        txt_buscar = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        lbl_totalregistros = new javax.swing.JLabel();
        lbl_totalordendecompra = new javax.swing.JLabel();
        lbl_totalordendecompra1 = new javax.swing.JLabel();
        lbl_totalordendecompra2 = new javax.swing.JLabel();
        lbl_totalordendecompra3 = new javax.swing.JLabel();
        txt_totalneto = new javax.swing.JTextField();
        txt_TotalEntrada = new javax.swing.JTextField();
        txt_DescuentoTotal = new javax.swing.JTextField();
        txt_ImpuestoTotal = new javax.swing.JTextField();
        rd_ordencompra = new javax.swing.JRadioButton();
        rd_producto = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaInventario = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaDetalleProducto = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        txt_Salidas = new javax.swing.JTextField();
        txt_Saldo = new javax.swing.JTextField();
        txt_Entradas = new javax.swing.JTextField();
        lbl_totalordendecompra4 = new javax.swing.JLabel();
        txt_IdDetalleProducto = new javax.swing.JTextField();
        txt_NombreProductoDetalle = new javax.swing.JTextField();
        txt_EspecificacionProductoDetalle = new javax.swing.JTextField();
        txt_IdProveedor = new javax.swing.JTextField();
        txt_ImpuestoEntrada = new javax.swing.JTextField();
        txt_DescuentoEntrada = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txt_IdEntrada = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_Proveedor = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txt_EntregadoPor = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        btn_generarentrada = new javax.swing.JButton();
        dc_FechaEntrada = new com.toedter.calendar.JDateChooser();
        jLabel28 = new javax.swing.JLabel();
        txt_Receptor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setText("Producto");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setText("Marca");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setText("Unidad COMPRA");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setText("Precio Neto");

        txt_IdProducto.setPreferredSize(new java.awt.Dimension(30, 25));
        txt_IdProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdProductoActionPerformed(evt);
            }
        });

        txt_EspecificacionProducto.setPreferredSize(new java.awt.Dimension(30, 25));

        txt_MarcaProducto.setPreferredSize(new java.awt.Dimension(30, 25));

        txt_PrecioNeto.setPreferredSize(new java.awt.Dimension(30, 25));

        btn_cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_cancelar.setText("Cancelar");

        txt_UnidadCompra.setPreferredSize(new java.awt.Dimension(30, 25));

        txt_IdUnidadCompra.setPreferredSize(new java.awt.Dimension(30, 25));
        txt_IdUnidadCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdUnidadCompraActionPerformed(evt);
            }
        });

        btn_buscarunidadcompra.setText("jButton1");
        btn_buscarunidadcompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarunidadcompraActionPerformed(evt);
            }
        });

        txt_NombreProducto.setPreferredSize(new java.awt.Dimension(30, 25));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel13.setText("Descuento (%)");

        txt_DescuentoProdEnt.setPreferredSize(new java.awt.Dimension(30, 25));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Impuesto (%)");

        txt_ImpuestoProdEnt.setPreferredSize(new java.awt.Dimension(30, 25));

        Subtotal.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Subtotal.setText("Subtotal");

        txt_SubtotalProdEnt.setPreferredSize(new java.awt.Dimension(30, 25));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setText("Especificacion");

        btn_buscarproducto.setText("jButton1");
        btn_buscarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarproductoActionPerformed(evt);
            }
        });

        btn_nuevo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_nuevo1.setText("Nuevo");
        btn_nuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevo1ActionPerformed(evt);
            }
        });

        btn_guardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        Subtotal1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Subtotal1.setText("Estado Producto");

        cbo_EstadoProDent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin novedades", "Falta cantidad", "Defectuoso", " " }));

        Subtotal2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Subtotal2.setText("Observaciones");

        txt_ObservacionEstado.setPreferredSize(new java.awt.Dimension(30, 25));

        txt_IdUnidadProducto.setPreferredSize(new java.awt.Dimension(30, 25));
        txt_IdUnidadProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdUnidadProductoActionPerformed(evt);
            }
        });

        txt_RelacionUcUp.setPreferredSize(new java.awt.Dimension(30, 25));
        txt_RelacionUcUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_RelacionUcUpActionPerformed(evt);
            }
        });

        txt_CantEntInventario.setPreferredSize(new java.awt.Dimension(30, 25));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("Cantidad Inventario");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setText("Relacion unidades Uu/Uc");

        txt_CantidadProducto.setPreferredSize(new java.awt.Dimension(30, 25));

        txt_IdDetalleEntrada.setPreferredSize(new java.awt.Dimension(30, 25));
        txt_IdDetalleEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdDetalleEntradaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setText("Cantidad Ucompra");

        txt_UnidadProducto.setPreferredSize(new java.awt.Dimension(30, 25));
        txt_UnidadProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UnidadProductoActionPerformed(evt);
            }
        });

        txt_CantSalInventario.setText("0");
        txt_CantSalInventario.setPreferredSize(new java.awt.Dimension(30, 25));
        txt_CantSalInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CantSalInventarioActionPerformed(evt);
            }
        });

        txt_FechaOrden.setPreferredSize(new java.awt.Dimension(30, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbo_EstadoProDent, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Subtotal1))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Subtotal2)
                                    .addComponent(txt_ObservacionEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(btn_nuevo1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_guardar))
                                    .addComponent(txt_ImpuestoProdEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_SubtotalProdEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Subtotal)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_DescuentoProdEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_CantEntInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_RelacionUcUp, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(txt_PrecioNeto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_MarcaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_UnidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(150, 150, 150)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_EspecificacionProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_CantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_IdUnidadCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(txt_UnidadCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_buscarunidadcompra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(txt_CantSalInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(txt_FechaOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txt_NombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_buscarproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_IdDetalleEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_IdUnidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_IdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_CantSalInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_FechaOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_NombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscarproducto)
                    .addComponent(txt_IdDetalleEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_IdUnidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_IdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_MarcaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_EspecificacionProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_UnidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_CantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_UnidadCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscarunidadcompra)
                    .addComponent(txt_IdUnidadCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_RelacionUcUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_CantEntInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_DescuentoProdEnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_PrecioNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Subtotal)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_SubtotalProdEnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ImpuestoProdEnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Subtotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Subtotal1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ObservacionEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_EstadoProDent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_guardar)
                    .addComponent(btn_nuevo1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Jpanel56.setBackground(new java.awt.Color(0, 255, 204));
        Jpanel56.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        TablaListado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TablaListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "1.IdOrdenCompra", "2.IdProducto", "3.NombreProducto", "4.Especificacion", "5.IdUnidadCompra", "6.UnidadOrdenCompra", "7.MarcaProducto", "8.CantidadCompra", "9.PrecioNeto", "10.DescuentoProducto", "11.ImpuestoProducto", "12.SubtotalProducto"
            }
        ));
        TablaListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaListadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaListado);

        btn_buscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.setToolTipText("");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_eliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        lbl_totalregistros.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_totalregistros.setText("Total Registros");
        lbl_totalregistros.setToolTipText("");

        lbl_totalordendecompra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_totalordendecompra.setText("Impuesto %");
        lbl_totalordendecompra.setToolTipText("");

        lbl_totalordendecompra1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_totalordendecompra1.setText("Total ");
        lbl_totalordendecompra1.setToolTipText("");

        lbl_totalordendecompra2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_totalordendecompra2.setText("Subtotal");
        lbl_totalordendecompra2.setToolTipText("");

        lbl_totalordendecompra3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_totalordendecompra3.setText("Descuento %");
        lbl_totalordendecompra3.setToolTipText("");

        txt_totalneto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_totalneto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_totalneto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalnetoActionPerformed(evt);
            }
        });

        txt_TotalEntrada.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_TotalEntrada.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txt_DescuentoTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_DescuentoTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txt_ImpuestoTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_ImpuestoTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        rd_ordencompra.setText("Por orden");
        rd_ordencompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rd_ordencompraMouseClicked(evt);
            }
        });

        rd_producto.setText("Por producto");
        rd_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rd_productoMouseClicked(evt);
            }
        });
        rd_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_productoActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Descuentos/Impuestos");

        TablaInventario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Producto", "Especificacion", "Unidad", "Entradas", "Salidas", "Saldo", "Precio Promedio", "Valor Totall"
            }
        ));
        TablaInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaInventarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaInventario);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("DETALLE PRODUCTO");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("ENTRADA ACTUAL");

        TablaDetalleProducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TablaDetalleProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha", "IdProducto", "Entrada", "Salida", "Saldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TablaDetalleProducto);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setText("INVENTARIO ACTUAL");

        txt_Salidas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_Salidas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_Salidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SalidasActionPerformed(evt);
            }
        });

        txt_Saldo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_Saldo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_Saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SaldoActionPerformed(evt);
            }
        });

        txt_Entradas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_Entradas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_Entradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EntradasActionPerformed(evt);
            }
        });

        lbl_totalordendecompra4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_totalordendecompra4.setText("Totales");
        lbl_totalordendecompra4.setToolTipText("");

        txt_IdDetalleProducto.setPreferredSize(new java.awt.Dimension(30, 25));

        txt_NombreProductoDetalle.setPreferredSize(new java.awt.Dimension(30, 25));

        txt_EspecificacionProductoDetalle.setPreferredSize(new java.awt.Dimension(30, 25));

        txt_IdProveedor.setPreferredSize(new java.awt.Dimension(30, 25));
        txt_IdProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdProveedorActionPerformed(evt);
            }
        });

        txt_ImpuestoEntrada.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_ImpuestoEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ImpuestoEntrada.setPreferredSize(new java.awt.Dimension(30, 25));

        txt_DescuentoEntrada.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_DescuentoEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_DescuentoEntrada.setPreferredSize(new java.awt.Dimension(30, 25));
        txt_DescuentoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DescuentoEntradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Jpanel56Layout = new javax.swing.GroupLayout(Jpanel56);
        Jpanel56.setLayout(Jpanel56Layout);
        Jpanel56Layout.setHorizontalGroup(
            Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel56Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jpanel56Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Jpanel56Layout.createSequentialGroup()
                        .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Jpanel56Layout.createSequentialGroup()
                                .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Jpanel56Layout.createSequentialGroup()
                                        .addComponent(txt_buscar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_buscar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_eliminar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_salir)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Jpanel56Layout.createSequentialGroup()
                                        .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(Jpanel56Layout.createSequentialGroup()
                                                .addComponent(txt_IdDetalleProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_NombreProductoDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_EspecificacionProductoDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel20))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel56Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel56Layout.createSequentialGroup()
                                        .addComponent(txt_IdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_totalordendecompra4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_Entradas, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_Salidas, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(txt_Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Jpanel56Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Jpanel56Layout.createSequentialGroup()
                                        .addComponent(rd_ordencompra)
                                        .addGap(163, 163, 163)
                                        .addComponent(lbl_totalregistros))
                                    .addComponent(rd_producto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(Jpanel56Layout.createSequentialGroup()
                                        .addComponent(lbl_totalordendecompra2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_totalneto, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Jpanel56Layout.createSequentialGroup()
                                        .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(Jpanel56Layout.createSequentialGroup()
                                                .addComponent(lbl_totalordendecompra1)
                                                .addGap(109, 109, 109))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel56Layout.createSequentialGroup()
                                                .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(Jpanel56Layout.createSequentialGroup()
                                                        .addComponent(lbl_totalordendecompra)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txt_DescuentoEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(Jpanel56Layout.createSequentialGroup()
                                                        .addComponent(lbl_totalordendecompra3)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(txt_ImpuestoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(50, 50, 50)))
                                        .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_TotalEntrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_ImpuestoTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_DescuentoTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap())))
        );
        Jpanel56Layout.setVerticalGroup(
            Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel56Layout.createSequentialGroup()
                .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(1, 1, 1)
                .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_IdDetalleProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_buscar)
                        .addComponent(btn_eliminar)
                        .addComponent(btn_salir)
                        .addComponent(txt_NombreProductoDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_EspecificacionProductoDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jpanel56Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(Jpanel56Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Jpanel56Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Entradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_totalordendecompra4)
                                    .addComponent(txt_Salidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel56Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_IdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jpanel56Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rd_ordencompra)
                            .addComponent(lbl_totalregistros))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rd_producto))
                    .addGroup(Jpanel56Layout.createSequentialGroup()
                        .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_totalneto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_totalordendecompra2))
                        .addGap(3, 3, 3)
                        .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_DescuentoTotal)
                            .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_totalordendecompra3)
                                .addComponent(txt_ImpuestoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ImpuestoTotal)
                            .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_totalordendecompra)
                                .addComponent(txt_DescuentoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_TotalEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_totalordendecompra1))))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        txt_IdEntrada.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_IdEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_IdEntrada.setText("0");
        txt_IdEntrada.setPreferredSize(new java.awt.Dimension(30, 25));
        txt_IdEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdEntradaActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Recibido por");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Proveedor");

        txt_Proveedor.setPreferredSize(new java.awt.Dimension(30, 25));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Fecha ");

        txt_EntregadoPor.setPreferredSize(new java.awt.Dimension(30, 25));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Entregado por");

        btn_generarentrada.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_generarentrada.setText("GENERAR ENTRADA");
        btn_generarentrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarentradaActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setText("#");

        txt_Receptor.setPreferredSize(new java.awt.Dimension(30, 25));
        txt_Receptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ReceptorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_generarentrada, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(38, 38, 38)
                        .addComponent(txt_IdEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dc_FechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_EntregadoPor, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(txt_Receptor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_generarentrada, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txt_IdEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(dc_FechaEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(7, 7, 7)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addComponent(jLabel17))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel25)
                                    .addGap(30, 30, 30)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txt_EntregadoPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_Receptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jpanel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(Jpanel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_IdProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdProductoActionPerformed

    private void txt_IdUnidadCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdUnidadCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdUnidadCompraActionPerformed

    private void btn_buscarunidadcompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarunidadcompraActionPerformed

        texto = "DETALLEENTRADA";

        VVistaUnidadCompra form = new VVistaUnidadCompra();
        form.lbl_conversion.setText(texto);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_btn_buscarunidadcompraActionPerformed

    private void btn_buscarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarproductoActionPerformed

        texto = "DETALLEENTRADA";

        VVistaProducto form = new VVistaProducto();

        form.lbl_conversion.setText(texto);
        form.toFront();
        form.setVisible(true);

    }//GEN-LAST:event_btn_buscarproductoActionPerformed

    private void btn_nuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevo1ActionPerformed
        habilitar();
        btn_guardar.setText("Guardar");
        accion = "guardar";
    }//GEN-LAST:event_btn_nuevo1ActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed

        if (txt_NombreProducto.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar PROVEEDOR");
            txt_NombreProducto.requestFocus();
            return;
        }

        if (txt_EspecificacionProducto.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar DESCUENTO");
            txt_EspecificacionProducto.requestFocus();
            return;
        }

        if (txt_CantidadProducto.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar NEGOCIADOR");
            txt_CantidadProducto.requestFocus();
            return;
        }

        if (txt_MarcaProducto.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar TIPO ORDEN");
            txt_MarcaProducto.requestFocus();
            return;
        }

        if (txt_UnidadCompra.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar TOTAL ORDEN");
            txt_UnidadCompra.requestFocus();
            return;
        }
        if (txt_PrecioNeto.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar TOTAL ORDEN");
            txt_PrecioNeto.requestFocus();
            return;
        }
        if (txt_DescuentoProdEnt.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar TOTAL ORDEN");
            txt_DescuentoProdEnt.requestFocus();
            return;
        }

        if (txt_ImpuestoProdEnt.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar IMPUESTO");
            txt_ImpuestoProdEnt.requestFocus();
            return;
        }

        if (txt_ObservacionEstado.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar OBSERVACIONES");
            txt_ObservacionEstado.requestFocus();
            return;
        }
        //CREAMOS UN NUEVO OBJETOVPRODUCTO Y FPRODUCTO VIDEO 8 MIN 4:50
        MDetalleEntradaAlmacen dts = new MDetalleEntradaAlmacen();
        CDetalleEntradaAlmacen func = new CDetalleEntradaAlmacen();

        subtotalproducto = (Double.parseDouble(txt_CantidadProducto.getText())) * (Double.parseDouble(txt_PrecioNeto.getText()));
        descuentoproducto = subtotalproducto * (Double.parseDouble(txt_DescuentoProdEnt.getText())) / 100;
        impuestoproducto = subtotalproducto * (Double.parseDouble(txt_ImpuestoProdEnt.getText())) / 100;
        cantinventario = (Double.parseDouble(txt_CantidadProducto.getText())) * (Double.parseDouble(txt_RelacionUcUp.getText()));
        txt_SubtotalProdEnt.setText(Double.toString(subtotalproducto));
        txt_CantEntInventario.setText(Double.toString(cantinventario));

        dts.setIdEntrada(Integer.parseInt(txt_IdEntrada.getText()));
        Calendar cal;
        int d, m, a;
        cal = dc_FechaEntrada.getCalendar();
        d = cal.get(Calendar.DAY_OF_MONTH);
        m = cal.get(Calendar.MONTH);
        a = cal.get(Calendar.YEAR) - 1900;
        dts.setFechaEntrada(new Date(a, m, d));

        dts.setIdProducto(Integer.parseInt(txt_IdProducto.getText()));
        dts.setIdUnidadCompra(Integer.parseInt(txt_IdUnidadCompra.getText()));
        dts.setIdUnidadProducto(Integer.parseInt(txt_IdUnidadProducto.getText()));
        dts.setRelacionUcUp(Double.parseDouble(txt_RelacionUcUp.getText()));
        dts.setMarcaProdEnt(txt_MarcaProducto.getText());
        dts.setCantidadEnt(Double.parseDouble(txt_CantidadProducto.getText()));
        dts.setCantEntInventario(Double.parseDouble(txt_CantEntInventario.getText()));
        dts.setCantSalInventario(Double.parseDouble(txt_CantSalInventario.getText()));
        dts.setPrecioNetoProdEnt(Double.parseDouble(txt_PrecioNeto.getText()));
        dts.setDescuentoProdEnt(descuentoproducto);
        //dts.setDescuentoProducto(Double.parseDouble(txt_DescuentoProducto.getText()));
        dts.setImpuestoProdEnt(impuestoproducto);
        dts.setSubTotalProdEnt(subtotalproducto + descuentoproducto + impuestoproducto);
        int seleccionado = cbo_EstadoProDent.getSelectedIndex();
        dts.setEstadoProdEnt((String) cbo_EstadoProDent.getItemAt(seleccionado));
        dts.setObservacionEstado(txt_ObservacionEstado.getText());

        if (accion.equals("guardar")) {

            if (func.insertar(dts)) {
                JOptionPane.showMessageDialog(rootPane, "El DETALLE ORDEN fue REGISTRADO satisfactoriamente");
                mostrar(txt_IdEntrada.getText());
                inhabilitar();
            }
        } else if (accion.equals("editar")) {
            dts.setIdDetalleEntrada(Integer.parseInt(txt_IdDetalleEntrada.getText()));
            if (func.editar(dts)) {
                JOptionPane.showMessageDialog(rootPane, "La UNIDAD DE MEDIDA fue EDITADA satisfactoriamente");
                mostrar(txt_IdEntrada.getText());
                //mostrar("");
                inhabilitar();
            }

        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void txt_IdUnidadProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdUnidadProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdUnidadProductoActionPerformed

    private void txt_RelacionUcUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_RelacionUcUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_RelacionUcUpActionPerformed

    private void txt_IdDetalleEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdDetalleEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdDetalleEntradaActionPerformed

    private void txt_UnidadProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UnidadProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UnidadProductoActionPerformed

    private void txt_CantSalInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CantSalInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CantSalInventarioActionPerformed

    private void TablaListadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaListadoMouseClicked

        // TODO add your handling code here:
        //EVENTO PARA ENVIAR DATOS DE LA TABLA HACIA CADA CAJA DE TEXTO Y OCMBO
        btn_guardar.setText("Editar");
        habilitar();
        //btn_buscarUuniversal.setEnabled(false);
        btn_eliminar.setEnabled(true);
        accion = "editar";
        //DE LA TABLA LISTADO SE ALMACENA EN UNA VARIABLE LA FILA DONDE SE HA DADO CLICK
        int fila = TablaListado.rowAtPoint(evt.getPoint());
        //CAPTURAMOS LOS DATOS DE CADA COLUMNA DE LA TABLA HABITACION PARA ENVIAR
        //A LA CAJA DE TEXTO

        txt_IdDetalleEntrada.setText(TablaListado.getValueAt(fila, 0).toString());
        txt_IdEntrada.setText(TablaListado.getValueAt(fila, 1).toString());
        //LA fecha solo se puede cambiar desde el dc_FechaEntrada directamente
        txt_IdProducto.setText(TablaListado.getValueAt(fila, 3).toString());
        txt_NombreProducto.setText(TablaListado.getValueAt(fila, 4).toString());
        txt_EspecificacionProducto.setText(TablaListado.getValueAt(fila, 5).toString());
        txt_IdUnidadCompra.setText(TablaListado.getValueAt(fila, 6).toString());
        txt_UnidadCompra.setText(TablaListado.getValueAt(fila, 7).toString());
        txt_IdUnidadProducto.setText(TablaListado.getValueAt(fila, 8).toString());
        txt_UnidadProducto.setText(TablaListado.getValueAt(fila, 9).toString());
        txt_RelacionUcUp.setText(TablaListado.getValueAt(fila, 10).toString());
        txt_MarcaProducto.setText(TablaListado.getValueAt(fila, 11).toString());
        txt_CantidadProducto.setText(TablaListado.getValueAt(fila, 12).toString());
        txt_CantEntInventario.setText(TablaListado.getValueAt(fila, 13).toString());
        txt_CantSalInventario.setText(TablaListado.getValueAt(fila, 14).toString());
        txt_PrecioNeto.setText(TablaListado.getValueAt(fila, 15).toString());
        txt_DescuentoProdEnt.setText(TablaListado.getValueAt(fila, 16).toString());
        txt_ImpuestoProdEnt.setText(TablaListado.getValueAt(fila, 17).toString());
        txt_SubtotalProdEnt.setText(TablaListado.getValueAt(fila, 18).toString());
        cbo_EstadoProDent.setSelectedItem(TablaListado.getValueAt(fila, 19).toString());
        txt_ObservacionEstado.setText(TablaListado.getValueAt(fila, 20).toString());
    }//GEN-LAST:event_TablaListadoMouseClicked

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        mostrar(txt_IdEntrada.getText());
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed

        if (!txt_IdDetalleEntrada.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Estas seguro de ELIMINAR el trabajador?", "confirmar", 2);
            if (confirmacion == 0) {
                CDetalleEntradaAlmacen func = new CDetalleEntradaAlmacen();
                MDetalleEntradaAlmacen dts = new MDetalleEntradaAlmacen();
                dts.setIdDetalleEntrada(Integer.parseInt(txt_IdDetalleEntrada.getText()));
                func.Eliminar(dts);
                mostrar(txt_IdEntrada.getText());
                // mostrar("");
                JOptionPane.showMessageDialog(rootPane, "La ENTRADA fue ELIMINADA satisfactoriamente");
                inhabilitar();
            }

        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_salirActionPerformed

    private void txt_totalnetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalnetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalnetoActionPerformed

    private void rd_ordencompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rd_ordencompraMouseClicked

    }//GEN-LAST:event_rd_ordencompraMouseClicked

    private void rd_productoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rd_productoMouseClicked

    }//GEN-LAST:event_rd_productoMouseClicked

    private void rd_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_productoActionPerformed

    private void TablaInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaInventarioMouseClicked
        int fila = TablaInventario.rowAtPoint(evt.getPoint());
        //CAPTURAMOS LOS DATOS DE CADA COLUMNA DE LA TABLA HABITACION PARA ENVIAR
        //A LA CAJA DE TEXTO

        txt_IdDetalleProducto.setText(TablaInventario.getValueAt(fila, 0).toString());
        txt_NombreProductoDetalle.setText(TablaInventario.getValueAt(fila, 1).toString());
        txt_EspecificacionProductoDetalle.setText(TablaInventario.getValueAt(fila, 2).toString());

        mostrarDetalleProducto(txt_IdDetalleProducto.getText());
        ocultar_detalleProducto();
    }//GEN-LAST:event_TablaInventarioMouseClicked

    private void txt_SalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SalidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SalidasActionPerformed

    private void txt_SaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SaldoActionPerformed

    private void txt_EntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EntradasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EntradasActionPerformed

    private void txt_IdProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdProveedorActionPerformed

    private void txt_DescuentoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DescuentoEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DescuentoEntradaActionPerformed

    private void txt_IdEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdEntradaActionPerformed

    private void btn_generarentradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarentradaActionPerformed

        VEntradaAlmacenConFactura form = new VEntradaAlmacenConFactura();
        form.toFront();
        form.setVisible(true);

    }//GEN-LAST:event_btn_generarentradaActionPerformed

    private void txt_ReceptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ReceptorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ReceptorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificacionesPresupuestales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificacionesPresupuestales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificacionesPresupuestales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificacionesPresupuestales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificacionesPresupuestales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpanel56;
    private javax.swing.JLabel Subtotal;
    private javax.swing.JLabel Subtotal1;
    private javax.swing.JLabel Subtotal2;
    private javax.swing.JTable TablaDetalleProducto;
    private javax.swing.JTable TablaInventario;
    private javax.swing.JTable TablaListado;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_buscarproducto;
    private javax.swing.JButton btn_buscarunidadcompra;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_eliminar;
    public static javax.swing.JButton btn_generarentrada;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_nuevo1;
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox<String> cbo_EstadoProDent;
    public static com.toedter.calendar.JDateChooser dc_FechaEntrada;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_totalordendecompra;
    private javax.swing.JLabel lbl_totalordendecompra1;
    private javax.swing.JLabel lbl_totalordendecompra2;
    private javax.swing.JLabel lbl_totalordendecompra3;
    private javax.swing.JLabel lbl_totalordendecompra4;
    private javax.swing.JLabel lbl_totalregistros;
    private javax.swing.JRadioButton rd_ordencompra;
    private javax.swing.JRadioButton rd_producto;
    private javax.swing.JTextField txt_CantEntInventario;
    private javax.swing.JTextField txt_CantSalInventario;
    private javax.swing.JTextField txt_CantidadProducto;
    public static javax.swing.JTextField txt_DescuentoEntrada;
    private javax.swing.JTextField txt_DescuentoProdEnt;
    private javax.swing.JTextField txt_DescuentoTotal;
    private javax.swing.JTextField txt_Entradas;
    public static javax.swing.JTextField txt_EntregadoPor;
    public static javax.swing.JTextField txt_EspecificacionProducto;
    public static javax.swing.JTextField txt_EspecificacionProductoDetalle;
    public static javax.swing.JTextField txt_FechaOrden;
    public static javax.swing.JTextField txt_IdDetalleEntrada;
    public static javax.swing.JTextField txt_IdDetalleProducto;
    public static javax.swing.JTextField txt_IdEntrada;
    public static javax.swing.JTextField txt_IdProducto;
    public static javax.swing.JTextField txt_IdProveedor;
    public static javax.swing.JTextField txt_IdUnidadCompra;
    public static javax.swing.JTextField txt_IdUnidadProducto;
    public static javax.swing.JTextField txt_ImpuestoEntrada;
    private javax.swing.JTextField txt_ImpuestoProdEnt;
    private javax.swing.JTextField txt_ImpuestoTotal;
    private javax.swing.JTextField txt_MarcaProducto;
    public static javax.swing.JTextField txt_NombreProducto;
    public static javax.swing.JTextField txt_NombreProductoDetalle;
    private javax.swing.JTextField txt_ObservacionEstado;
    private javax.swing.JTextField txt_PrecioNeto;
    public static javax.swing.JTextField txt_Proveedor;
    public static javax.swing.JTextField txt_Receptor;
    public static javax.swing.JTextField txt_RelacionUcUp;
    private javax.swing.JTextField txt_Saldo;
    private javax.swing.JTextField txt_Salidas;
    private javax.swing.JTextField txt_SubtotalProdEnt;
    private javax.swing.JTextField txt_TotalEntrada;
    public static javax.swing.JTextField txt_UnidadCompra;
    public static javax.swing.JTextField txt_UnidadProducto;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_totalneto;
    // End of variables declaration//GEN-END:variables
}
