/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebas;

/**
 *
 * @author Gladys Lopera
 */
public class VAvances extends javax.swing.JFrame {

    /**
     * Creates new form Modificaciones
     */
    public VAvances() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_EspecificacionProducto = new javax.swing.JTextField();
        btn_cancelar = new javax.swing.JButton();
        txt_NombreProducto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_DescuentoProdEnt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Subtotal = new javax.swing.JLabel();
        btn_nuevo1 = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        Subtotal1 = new javax.swing.JLabel();
        Subtotal2 = new javax.swing.JLabel();
        txt_AcumSubtoAnteior = new javax.swing.JTextField();
        txt_CantEntInventario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_UnidadItem = new javax.swing.JTextField();
        txt_CantSalInventario = new javax.swing.JTextField();
        txt_IdPresupuesto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dc_FechaEntrada = new com.toedter.calendar.JDateChooser();
        jLabel22 = new javax.swing.JLabel();
        cbo_EstadoProDent1 = new javax.swing.JComboBox<>();
        txt_SubTotalAvance = new javax.swing.JTextField();
        txt_PrecioContratado = new javax.swing.JTextField();
        txt_SubTotalContratado = new javax.swing.JTextField();
        Subtotal3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_CantAcumAnterior = new javax.swing.JTextField();
        txt_CantAcumActual = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Subtotal4 = new javax.swing.JLabel();
        txt_AcumSubtoActual = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_CantSaldoActual = new javax.swing.JTextField();
        txt_SaldoActual = new javax.swing.JTextField();
        Subtotal5 = new javax.swing.JLabel();
        btn_buscar1 = new javax.swing.JButton();
        txt_EspecificacionProducto1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txt_IdItem1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txt_buscar = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaInventario = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        txt_IdDetalleProducto = new javax.swing.JTextField();
        txt_NombreProductoDetalle = new javax.swing.JTextField();
        txt_EspecificacionProductoDetalle = new javax.swing.JTextField();
        txt_IdProveedor = new javax.swing.JTextField();
        lbl_totalordendecompra4 = new javax.swing.JLabel();
        txt_Entradas = new javax.swing.JTextField();
        txt_Salidas = new javax.swing.JTextField();
        txt_Saldo = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaDetalleProducto = new javax.swing.JTable();
        Jpanel56 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaListado = new javax.swing.JTable();
        lbl_totalregistros = new javax.swing.JLabel();
        lbl_totalordendecompra = new javax.swing.JLabel();
        lbl_totalordendecompra1 = new javax.swing.JLabel();
        lbl_totalordendecompra2 = new javax.swing.JLabel();
        lbl_totalordendecompra3 = new javax.swing.JLabel();
        txt_totalneto = new javax.swing.JTextField();
        txt_TotalEntrada = new javax.swing.JTextField();
        txt_DescuentoTotal = new javax.swing.JTextField();
        txt_ImpuestoTotal = new javax.swing.JTextField();
        rd_ordencompra = new javax.swing.JRadioButton();
        rd_producto = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        txt_ImpuestoEntrada = new javax.swing.JTextField();
        txt_DescuentoEntrada = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MODIFICACIONES PRESUPUESTALES");
        setBackground(new java.awt.Color(51, 51, 255));
        setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        setForeground(new java.awt.Color(153, 51, 255));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 2), "INFORMACION GENERAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 0, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Codigo Item");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Nombre Item");

        txt_EspecificacionProducto.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txt_EspecificacionProducto.setForeground(new java.awt.Color(0, 0, 102));
        txt_EspecificacionProducto.setPreferredSize(new java.awt.Dimension(30, 25));

        btn_cancelar.setBackground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_cancelar.setForeground(new java.awt.Color(0, 0, 102));
        btn_cancelar.setText("Cancelar");

        txt_NombreProducto.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txt_NombreProducto.setForeground(new java.awt.Color(0, 0, 102));
        txt_NombreProducto.setPreferredSize(new java.awt.Dimension(30, 25));

        jLabel13.setBackground(new java.awt.Color(0, 0, 102));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setText("Cantidad Avance");

        txt_DescuentoProdEnt.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txt_DescuentoProdEnt.setForeground(new java.awt.Color(0, 0, 102));
        txt_DescuentoProdEnt.setPreferredSize(new java.awt.Dimension(30, 25));

        jLabel14.setBackground(new java.awt.Color(0, 0, 102));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setText("Estado Actual");

        Subtotal.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Subtotal.setForeground(new java.awt.Color(0, 0, 102));
        Subtotal.setText("PrecioContratado");

        btn_nuevo1.setBackground(new java.awt.Color(255, 255, 255));
        btn_nuevo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_nuevo1.setForeground(new java.awt.Color(0, 0, 102));
        btn_nuevo1.setText("Nuevo");
        btn_nuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevo1ActionPerformed(evt);
            }
        });

        btn_guardar.setBackground(new java.awt.Color(255, 255, 255));
        btn_guardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_guardar.setForeground(new java.awt.Color(0, 0, 102));
        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        Subtotal1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Subtotal1.setForeground(new java.awt.Color(0, 0, 102));
        Subtotal1.setText("Subtotal Avance");

        Subtotal2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Subtotal2.setForeground(new java.awt.Color(0, 0, 102));
        Subtotal2.setText("Acumu Subtotal Anterior");

        txt_AcumSubtoAnteior.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txt_AcumSubtoAnteior.setForeground(new java.awt.Color(0, 0, 102));
        txt_AcumSubtoAnteior.setPreferredSize(new java.awt.Dimension(30, 25));

        txt_CantEntInventario.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txt_CantEntInventario.setForeground(new java.awt.Color(0, 0, 102));
        txt_CantEntInventario.setPreferredSize(new java.awt.Dimension(30, 25));

        jLabel5.setBackground(new java.awt.Color(0, 0, 102));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Cantidad Contractual");

        txt_UnidadItem.setPreferredSize(new java.awt.Dimension(30, 25));
        txt_UnidadItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UnidadItemActionPerformed(evt);
            }
        });

        txt_CantSalInventario.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txt_CantSalInventario.setForeground(new java.awt.Color(0, 0, 102));
        txt_CantSalInventario.setText("0");
        txt_CantSalInventario.setPreferredSize(new java.awt.Dimension(30, 25));
        txt_CantSalInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CantSalInventarioActionPerformed(evt);
            }
        });

        txt_IdPresupuesto.setPreferredSize(new java.awt.Dimension(30, 25));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("ID Avance");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("ID Presup");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText("ID Item");

        dc_FechaEntrada.setForeground(new java.awt.Color(0, 0, 102));
        dc_FechaEntrada.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 102));
        jLabel22.setText("Fecha de avance");

        cbo_EstadoProDent1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        cbo_EstadoProDent1.setForeground(new java.awt.Color(0, 0, 102));
        cbo_EstadoProDent1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo", "Abierto", "Cerrado", "Suspendido", "Eliminado", "Otro", " " }));
        cbo_EstadoProDent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_EstadoProDent1ActionPerformed(evt);
            }
        });

        txt_SubTotalAvance.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txt_SubTotalAvance.setForeground(new java.awt.Color(0, 0, 102));
        txt_SubTotalAvance.setPreferredSize(new java.awt.Dimension(30, 25));

        txt_PrecioContratado.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txt_PrecioContratado.setForeground(new java.awt.Color(0, 0, 102));
        txt_PrecioContratado.setPreferredSize(new java.awt.Dimension(30, 25));

        txt_SubTotalContratado.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txt_SubTotalContratado.setForeground(new java.awt.Color(0, 0, 102));
        txt_SubTotalContratado.setPreferredSize(new java.awt.Dimension(30, 25));

        Subtotal3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Subtotal3.setForeground(new java.awt.Color(0, 0, 102));
        Subtotal3.setText("Subtotal COntrato");

        jLabel15.setBackground(new java.awt.Color(0, 0, 102));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 102));
        jLabel15.setText("Cantidad acu anterior");

        txt_CantAcumAnterior.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txt_CantAcumAnterior.setForeground(new java.awt.Color(0, 0, 102));
        txt_CantAcumAnterior.setPreferredSize(new java.awt.Dimension(30, 25));

        txt_CantAcumActual.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txt_CantAcumActual.setForeground(new java.awt.Color(0, 0, 102));
        txt_CantAcumActual.setPreferredSize(new java.awt.Dimension(30, 25));

        jLabel16.setBackground(new java.awt.Color(0, 0, 102));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 102));
        jLabel16.setText("Cantidad acu actual");

        Subtotal4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Subtotal4.setForeground(new java.awt.Color(0, 0, 102));
        Subtotal4.setText("Acumu Subtotal Actual");

        txt_AcumSubtoActual.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txt_AcumSubtoActual.setForeground(new java.awt.Color(0, 0, 102));
        txt_AcumSubtoActual.setPreferredSize(new java.awt.Dimension(30, 25));

        jLabel17.setBackground(new java.awt.Color(0, 0, 102));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 102));
        jLabel17.setText("Cant Saldo");

        txt_CantSaldoActual.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txt_CantSaldoActual.setForeground(new java.awt.Color(0, 0, 102));
        txt_CantSaldoActual.setPreferredSize(new java.awt.Dimension(30, 25));

        txt_SaldoActual.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txt_SaldoActual.setForeground(new java.awt.Color(0, 0, 102));
        txt_SaldoActual.setPreferredSize(new java.awt.Dimension(30, 25));

        Subtotal5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Subtotal5.setForeground(new java.awt.Color(0, 0, 102));
        Subtotal5.setText("Saldo Actual");

        btn_buscar1.setBackground(new java.awt.Color(255, 255, 255));
        btn_buscar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_buscar1.setForeground(new java.awt.Color(0, 0, 102));
        btn_buscar1.setText("GENERAR AVANCE");
        btn_buscar1.setToolTipText("");
        btn_buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar1ActionPerformed(evt);
            }
        });

        txt_EspecificacionProducto1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txt_EspecificacionProducto1.setForeground(new java.awt.Color(0, 0, 102));
        txt_EspecificacionProducto1.setPreferredSize(new java.awt.Dimension(30, 25));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 102));
        jLabel23.setText("Responsable");

        txt_IdItem1.setPreferredSize(new java.awt.Dimension(30, 25));
        txt_IdItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdItem1ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 102));
        jLabel18.setText("Unidad Item");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_CantAcumAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_CantAcumActual, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_DescuentoProdEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Subtotal1)
                                    .addComponent(txt_SubTotalAvance, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_AcumSubtoAnteior, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Subtotal2)
                                    .addComponent(Subtotal4)
                                    .addComponent(txt_AcumSubtoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Subtotal5)
                                    .addComponent(txt_SaldoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Subtotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Subtotal3))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_CantEntInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_PrecioContratado, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_SubTotalContratado, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_NombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_EspecificacionProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btn_nuevo1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbo_EstadoProDent1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_CantSaldoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14))
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_buscar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_EspecificacionProducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txt_CantSalInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_IdPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dc_FechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22))))
                    .addComponent(jLabel23)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_IdItem1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_UnidadItem, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_CantSalInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_IdPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(dc_FechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(txt_EspecificacionProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_buscar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_UnidadItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_IdItem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_EspecificacionProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_NombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Subtotal)
                    .addComponent(Subtotal3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_CantEntInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_PrecioContratado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_SubTotalContratado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Subtotal1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_SubTotalAvance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_DescuentoProdEnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Subtotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_AcumSubtoAnteior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_CantAcumAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(Subtotal4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_CantAcumActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_AcumSubtoActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(5, 5, 5)
                        .addComponent(txt_CantSaldoActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbo_EstadoProDent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_cancelar)
                            .addComponent(btn_guardar)
                            .addComponent(btn_nuevo1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Subtotal5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(txt_SaldoActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("AVANCE DE PROYECTO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addGap(482, 482, 482))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 951, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 2), "RESUMEN DE AVANCES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N

        txt_buscar.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txt_buscar.setForeground(new java.awt.Color(0, 0, 102));

        btn_buscar.setBackground(new java.awt.Color(255, 255, 255));
        btn_buscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_buscar.setForeground(new java.awt.Color(0, 0, 102));
        btn_buscar.setText("Buscar");
        btn_buscar.setToolTipText("");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_eliminar.setBackground(new java.awt.Color(255, 255, 255));
        btn_eliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_eliminar.setForeground(new java.awt.Color(0, 0, 102));
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_salir.setBackground(new java.awt.Color(255, 255, 255));
        btn_salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(0, 0, 102));
        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        TablaInventario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "AvanceNumero", "Fecha", "TotalAvance", "TotalAcumulado", "Saldo"
            }
        ));
        TablaInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaInventarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaInventario);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_salir)
                .addGap(561, 561, 561))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(537, 537, 537))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar)
                    .addComponent(btn_eliminar)
                    .addComponent(btn_salir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 2), "DETALLE DE AVANCE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N

        txt_IdDetalleProducto.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txt_IdDetalleProducto.setForeground(new java.awt.Color(0, 0, 102));
        txt_IdDetalleProducto.setPreferredSize(new java.awt.Dimension(30, 25));

        txt_NombreProductoDetalle.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txt_NombreProductoDetalle.setForeground(new java.awt.Color(0, 0, 102));
        txt_NombreProductoDetalle.setPreferredSize(new java.awt.Dimension(30, 25));

        txt_EspecificacionProductoDetalle.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txt_EspecificacionProductoDetalle.setForeground(new java.awt.Color(0, 0, 102));
        txt_EspecificacionProductoDetalle.setPreferredSize(new java.awt.Dimension(30, 25));

        txt_IdProveedor.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txt_IdProveedor.setForeground(new java.awt.Color(0, 0, 102));
        txt_IdProveedor.setPreferredSize(new java.awt.Dimension(30, 25));
        txt_IdProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdProveedorActionPerformed(evt);
            }
        });

        lbl_totalordendecompra4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_totalordendecompra4.setForeground(new java.awt.Color(0, 0, 102));
        lbl_totalordendecompra4.setText("Totales");
        lbl_totalordendecompra4.setToolTipText("");

        txt_Entradas.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txt_Entradas.setForeground(new java.awt.Color(0, 0, 102));
        txt_Entradas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_Entradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EntradasActionPerformed(evt);
            }
        });

        txt_Salidas.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txt_Salidas.setForeground(new java.awt.Color(0, 0, 102));
        txt_Salidas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_Salidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SalidasActionPerformed(evt);
            }
        });

        txt_Saldo.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txt_Saldo.setForeground(new java.awt.Color(0, 0, 102));
        txt_Saldo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_Saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SaldoActionPerformed(evt);
            }
        });

        TablaDetalleProducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TablaDetalleProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NombreItem", "CantEjecutadA", "TotalEjecutado", "%Ejecutado", "CantSaldo", "SaldoTotal", "%SaldoTotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TablaDetalleProducto);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txt_IdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_totalordendecompra4)
                        .addGap(18, 18, 18)
                        .addComponent(txt_Entradas, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Salidas, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txt_Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txt_IdDetalleProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_NombreProductoDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_EspecificacionProductoDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_IdDetalleProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_NombreProductoDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_EspecificacionProductoDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Entradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_totalordendecompra4)
                    .addComponent(txt_Salidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_IdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Jpanel56.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 2), "AVANCE ACTUAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N

        TablaListado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TablaListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "0.IdAvance", "1.IdITem", "2.CodigoItem", "3.NombreItem", "4.CantContratada", "5.PrecioContratado", "6.SubTotal", "7.CantAvance", "8.SubTotalAvance", "9.CAntAcuAnterior", "10.SubtotAcuActerior", "11.CAntAcuActual", "12.SubtoAcuActual", "13.SaldoCaant", "14.SaldoActual"
            }
        ));
        TablaListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaListadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaListado);

        lbl_totalregistros.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_totalregistros.setForeground(new java.awt.Color(0, 0, 102));
        lbl_totalregistros.setText("Total Registros");
        lbl_totalregistros.setToolTipText("");

        lbl_totalordendecompra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_totalordendecompra.setForeground(new java.awt.Color(0, 0, 102));
        lbl_totalordendecompra.setText("Impuesto %");
        lbl_totalordendecompra.setToolTipText("");

        lbl_totalordendecompra1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_totalordendecompra1.setForeground(new java.awt.Color(0, 0, 102));
        lbl_totalordendecompra1.setText("Total ");
        lbl_totalordendecompra1.setToolTipText("");

        lbl_totalordendecompra2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_totalordendecompra2.setForeground(new java.awt.Color(0, 0, 102));
        lbl_totalordendecompra2.setText("Subtotal");
        lbl_totalordendecompra2.setToolTipText("");

        lbl_totalordendecompra3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_totalordendecompra3.setForeground(new java.awt.Color(0, 0, 102));
        lbl_totalordendecompra3.setText("Descuento %");
        lbl_totalordendecompra3.setToolTipText("");

        txt_totalneto.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txt_totalneto.setForeground(new java.awt.Color(0, 0, 102));
        txt_totalneto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_totalneto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalnetoActionPerformed(evt);
            }
        });

        txt_TotalEntrada.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txt_TotalEntrada.setForeground(new java.awt.Color(0, 0, 102));
        txt_TotalEntrada.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txt_DescuentoTotal.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txt_DescuentoTotal.setForeground(new java.awt.Color(0, 0, 102));
        txt_DescuentoTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txt_ImpuestoTotal.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txt_ImpuestoTotal.setForeground(new java.awt.Color(0, 0, 102));
        txt_ImpuestoTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        rd_ordencompra.setText("Por orden");
        rd_ordencompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rd_ordencompraMouseClicked(evt);
            }
        });

        rd_producto.setText("Por producto");
        rd_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rd_productoMouseClicked(evt);
            }
        });
        rd_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_productoActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 102));
        jLabel26.setText("Descuentos/Impuestos");

        txt_ImpuestoEntrada.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txt_ImpuestoEntrada.setForeground(new java.awt.Color(0, 0, 102));
        txt_ImpuestoEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ImpuestoEntrada.setPreferredSize(new java.awt.Dimension(30, 25));

        txt_DescuentoEntrada.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txt_DescuentoEntrada.setForeground(new java.awt.Color(0, 0, 102));
        txt_DescuentoEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_DescuentoEntrada.setPreferredSize(new java.awt.Dimension(30, 25));
        txt_DescuentoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DescuentoEntradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Jpanel56Layout = new javax.swing.GroupLayout(Jpanel56);
        Jpanel56.setLayout(Jpanel56Layout);
        Jpanel56Layout.setHorizontalGroup(
            Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel56Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(Jpanel56Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Jpanel56Layout.createSequentialGroup()
                                .addComponent(rd_ordencompra)
                                .addGap(18, 18, 18)
                                .addComponent(rd_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)
                                .addComponent(lbl_totalregistros))
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                        .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Jpanel56Layout.createSequentialGroup()
                                .addComponent(lbl_totalordendecompra2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_totalneto, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Jpanel56Layout.createSequentialGroup()
                                .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel56Layout.createSequentialGroup()
                                        .addComponent(lbl_totalordendecompra)
                                        .addGap(40, 40, 40))
                                    .addGroup(Jpanel56Layout.createSequentialGroup()
                                        .addComponent(lbl_totalordendecompra3)
                                        .addGap(34, 34, 34)))
                                .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_ImpuestoEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_DescuentoEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_ImpuestoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_DescuentoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(Jpanel56Layout.createSequentialGroup()
                                .addComponent(lbl_totalordendecompra1)
                                .addGap(141, 141, 141)
                                .addComponent(txt_TotalEntrada)))
                        .addGap(11, 11, 11)))
                .addContainerGap())
        );
        Jpanel56Layout.setVerticalGroup(
            Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel56Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jpanel56Layout.createSequentialGroup()
                        .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Jpanel56Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lbl_totalordendecompra2)
                                .addGap(1, 1, 1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel56Layout.createSequentialGroup()
                                .addComponent(txt_totalneto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_totalordendecompra3)
                            .addComponent(txt_ImpuestoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_DescuentoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_DescuentoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_totalordendecompra)
                            .addComponent(txt_ImpuestoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Jpanel56Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rd_ordencompra)
                            .addComponent(rd_producto)
                            .addComponent(lbl_totalregistros))))
                .addGroup(Jpanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jpanel56Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lbl_totalordendecompra1))
                    .addGroup(Jpanel56Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_TotalEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(Jpanel56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jpanel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevo1ActionPerformed
        habilitar();
        btn_guardar.setText("Guardar");
        accion = "guardar";
    }//GEN-LAST:event_btn_nuevo1ActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed

        if (txt_NombreProducto.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar PROVEEDOR");
            txt_NombreProducto.requestFocus();
            return;
        }

        if (txt_EspecificacionProducto.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar DESCUENTO");
            txt_EspecificacionProducto.requestFocus();
            return;
        }

        if (txt_CantidadProducto.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar NEGOCIADOR");
            txt_CantidadProducto.requestFocus();
            return;
        }

        if (txt_MarcaProducto.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar TIPO ORDEN");
            txt_MarcaProducto.requestFocus();
            return;
        }

        if (txt_UnidadCompra.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar TOTAL ORDEN");
            txt_UnidadCompra.requestFocus();
            return;
        }
        if (txt_PrecioNeto.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar TOTAL ORDEN");
            txt_PrecioNeto.requestFocus();
            return;
        }
        if (txt_DescuentoProdEnt.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar TOTAL ORDEN");
            txt_DescuentoProdEnt.requestFocus();
            return;
        }

        if (txt_ImpuestoProdEnt.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar IMPUESTO");
            txt_ImpuestoProdEnt.requestFocus();
            return;
        }

        if (txt_AcumSubtoAnteior.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar OBSERVACIONES");
            txt_AcumSubtoAnteior.requestFocus();
            return;
        }
        //CREAMOS UN NUEVO OBJETOVPRODUCTO Y FPRODUCTO VIDEO 8 MIN 4:50
        MDetalleEntradaAlmacen dts = new MDetalleEntradaAlmacen();
        CDetalleEntradaAlmacen func = new CDetalleEntradaAlmacen();

        subtotalproducto = (Double.parseDouble(txt_CantidadProducto.getText())) * (Double.parseDouble(txt_PrecioNeto.getText()));
        descuentoproducto = subtotalproducto * (Double.parseDouble(txt_DescuentoProdEnt.getText())) / 100;
        impuestoproducto = subtotalproducto * (Double.parseDouble(txt_ImpuestoProdEnt.getText())) / 100;
        cantinventario = (Double.parseDouble(txt_CantidadProducto.getText())) * (Double.parseDouble(txt_RelacionUcUp.getText()));
        txt_SubtotalProdEnt.setText(Double.toString(subtotalproducto));
        txt_CantEntInventario.setText(Double.toString(cantinventario));

        dts.setIdEntrada(Integer.parseInt(txt_IdEntrada.getText()));
        Calendar cal;
        int d, m, a;
        cal = dc_FechaEntrada.getCalendar();
        d = cal.get(Calendar.DAY_OF_MONTH);
        m = cal.get(Calendar.MONTH);
        a = cal.get(Calendar.YEAR) - 1900;
        dts.setFechaEntrada(new Date(a, m, d));

        dts.setIdProducto(Integer.parseInt(txt_IdProducto.getText()));
        dts.setIdUnidadCompra(Integer.parseInt(txt_IdUnidadCompra.getText()));
        dts.setIdUnidadProducto(Integer.parseInt(txt_IdUnidadProducto.getText()));
        dts.setRelacionUcUp(Double.parseDouble(txt_RelacionUcUp.getText()));
        dts.setMarcaProdEnt(txt_MarcaProducto.getText());
        dts.setCantidadEnt(Double.parseDouble(txt_CantidadProducto.getText()));
        dts.setCantEntInventario(Double.parseDouble(txt_CantEntInventario.getText()));
        dts.setCantSalInventario(Double.parseDouble(txt_CantSalInventario.getText()));
        dts.setPrecioNetoProdEnt(Double.parseDouble(txt_PrecioNeto.getText()));
        dts.setDescuentoProdEnt(descuentoproducto);
        //dts.setDescuentoProducto(Double.parseDouble(txt_DescuentoProducto.getText()));
        dts.setImpuestoProdEnt(impuestoproducto);
        dts.setSubTotalProdEnt(subtotalproducto + descuentoproducto + impuestoproducto);
        int seleccionado = cbo_EstadoProDent.getSelectedIndex();
        dts.setEstadoProdEnt((String) cbo_EstadoProDent.getItemAt(seleccionado));
        dts.setObservacionEstado(txt_AcumSubtoAnteior.getText());

        if (accion.equals("guardar")) {

            if (func.insertar(dts)) {
                JOptionPane.showMessageDialog(rootPane, "El DETALLE ORDEN fue REGISTRADO satisfactoriamente");
                mostrar(txt_IdEntrada.getText());
                inhabilitar();
            }
        } else if (accion.equals("editar")) {
            dts.setIdDetalleEntrada(Integer.parseInt(txt_UnidadItem.getText()));
            if (func.editar(dts)) {
                JOptionPane.showMessageDialog(rootPane, "La UNIDAD DE MEDIDA fue EDITADA satisfactoriamente");
                mostrar(txt_IdEntrada.getText());
                //mostrar("");
                inhabilitar();
            }

        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void txt_UnidadItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UnidadItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UnidadItemActionPerformed

    private void txt_CantSalInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CantSalInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CantSalInventarioActionPerformed

    private void cbo_EstadoProDent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_EstadoProDent1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_EstadoProDent1ActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        mostrar(txt_IdEntrada.getText());
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed

        if (!txt_UnidadItem.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Estas seguro de ELIMINAR el trabajador?", "confirmar", 2);
            if (confirmacion == 0) {
                CDetalleEntradaAlmacen func = new CDetalleEntradaAlmacen();
                MDetalleEntradaAlmacen dts = new MDetalleEntradaAlmacen();
                dts.setIdDetalleEntrada(Integer.parseInt(txt_UnidadItem.getText()));
                func.Eliminar(dts);
                mostrar(txt_IdEntrada.getText());
                // mostrar("");
                JOptionPane.showMessageDialog(rootPane, "La ENTRADA fue ELIMINADA satisfactoriamente");
                inhabilitar();
            }

        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_salirActionPerformed

    private void TablaInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaInventarioMouseClicked
        int fila = TablaInventario.rowAtPoint(evt.getPoint());
        //CAPTURAMOS LOS DATOS DE CADA COLUMNA DE LA TABLA HABITACION PARA ENVIAR
        //A LA CAJA DE TEXTO

        txt_IdDetalleProducto.setText(TablaInventario.getValueAt(fila, 0).toString());
        txt_NombreProductoDetalle.setText(TablaInventario.getValueAt(fila, 1).toString());
        txt_EspecificacionProductoDetalle.setText(TablaInventario.getValueAt(fila, 2).toString());

        mostrarDetalleProducto(txt_IdDetalleProducto.getText());
        ocultar_detalleProducto();
    }//GEN-LAST:event_TablaInventarioMouseClicked

    private void txt_IdProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdProveedorActionPerformed

    private void txt_EntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EntradasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EntradasActionPerformed

    private void txt_SalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SalidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SalidasActionPerformed

    private void txt_SaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SaldoActionPerformed

    private void TablaListadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaListadoMouseClicked

        // TODO add your handling code here:
        //EVENTO PARA ENVIAR DATOS DE LA TABLA HACIA CADA CAJA DE TEXTO Y OCMBO
        btn_guardar.setText("Editar");
        habilitar();
        //btn_buscarUuniversal.setEnabled(false);
        btn_eliminar.setEnabled(true);
        accion = "editar";
        //DE LA TABLA LISTADO SE ALMACENA EN UNA VARIABLE LA FILA DONDE SE HA DADO CLICK
        int fila = TablaListado.rowAtPoint(evt.getPoint());
        //CAPTURAMOS LOS DATOS DE CADA COLUMNA DE LA TABLA HABITACION PARA ENVIAR
        //A LA CAJA DE TEXTO

        txt_UnidadItem.setText(TablaListado.getValueAt(fila, 0).toString());
        txt_IdEntrada.setText(TablaListado.getValueAt(fila, 1).toString());
        //LA fecha solo se puede cambiar desde el dc_FechaEntrada directamente
        txt_IdProducto.setText(TablaListado.getValueAt(fila, 3).toString());
        txt_NombreProducto.setText(TablaListado.getValueAt(fila, 4).toString());
        txt_EspecificacionProducto.setText(TablaListado.getValueAt(fila, 5).toString());
        txt_IdUnidadCompra.setText(TablaListado.getValueAt(fila, 6).toString());
        txt_UnidadCompra.setText(TablaListado.getValueAt(fila, 7).toString());
        txt_IdUnidadProducto.setText(TablaListado.getValueAt(fila, 8).toString());
        txt_UnidadProducto.setText(TablaListado.getValueAt(fila, 9).toString());
        txt_RelacionUcUp.setText(TablaListado.getValueAt(fila, 10).toString());
        txt_MarcaProducto.setText(TablaListado.getValueAt(fila, 11).toString());
        txt_CantidadProducto.setText(TablaListado.getValueAt(fila, 12).toString());
        txt_CantEntInventario.setText(TablaListado.getValueAt(fila, 13).toString());
        txt_CantSalInventario.setText(TablaListado.getValueAt(fila, 14).toString());
        txt_PrecioNeto.setText(TablaListado.getValueAt(fila, 15).toString());
        txt_DescuentoProdEnt.setText(TablaListado.getValueAt(fila, 16).toString());
        txt_ImpuestoProdEnt.setText(TablaListado.getValueAt(fila, 17).toString());
        txt_SubtotalProdEnt.setText(TablaListado.getValueAt(fila, 18).toString());
        cbo_EstadoProDent.setSelectedItem(TablaListado.getValueAt(fila, 19).toString());
        txt_AcumSubtoAnteior.setText(TablaListado.getValueAt(fila, 20).toString());
    }//GEN-LAST:event_TablaListadoMouseClicked

    private void txt_totalnetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalnetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalnetoActionPerformed

    private void rd_ordencompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rd_ordencompraMouseClicked

    }//GEN-LAST:event_rd_ordencompraMouseClicked

    private void rd_productoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rd_productoMouseClicked

    }//GEN-LAST:event_rd_productoMouseClicked

    private void rd_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_productoActionPerformed

    private void txt_DescuentoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DescuentoEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DescuentoEntradaActionPerformed

    private void btn_buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscar1ActionPerformed

    private void txt_IdItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VAvances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VAvances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VAvances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VAvances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VAvances().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpanel56;
    private javax.swing.JLabel Subtotal;
    private javax.swing.JLabel Subtotal1;
    private javax.swing.JLabel Subtotal2;
    private javax.swing.JLabel Subtotal3;
    private javax.swing.JLabel Subtotal4;
    private javax.swing.JLabel Subtotal5;
    private javax.swing.JTable TablaDetalleProducto;
    private javax.swing.JTable TablaInventario;
    private javax.swing.JTable TablaListado;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_buscar1;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_nuevo1;
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox<String> cbo_EstadoProDent1;
    public static com.toedter.calendar.JDateChooser dc_FechaEntrada;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_totalordendecompra;
    private javax.swing.JLabel lbl_totalordendecompra1;
    private javax.swing.JLabel lbl_totalordendecompra2;
    private javax.swing.JLabel lbl_totalordendecompra3;
    private javax.swing.JLabel lbl_totalordendecompra4;
    private javax.swing.JLabel lbl_totalregistros;
    private javax.swing.JRadioButton rd_ordencompra;
    private javax.swing.JRadioButton rd_producto;
    private javax.swing.JTextField txt_AcumSubtoActual;
    private javax.swing.JTextField txt_AcumSubtoAnteior;
    private javax.swing.JTextField txt_CantAcumActual;
    private javax.swing.JTextField txt_CantAcumAnterior;
    private javax.swing.JTextField txt_CantEntInventario;
    private javax.swing.JTextField txt_CantSalInventario;
    private javax.swing.JTextField txt_CantSaldoActual;
    public static javax.swing.JTextField txt_DescuentoEntrada;
    private javax.swing.JTextField txt_DescuentoProdEnt;
    private javax.swing.JTextField txt_DescuentoTotal;
    private javax.swing.JTextField txt_Entradas;
    public static javax.swing.JTextField txt_EspecificacionProducto;
    public static javax.swing.JTextField txt_EspecificacionProducto1;
    public static javax.swing.JTextField txt_EspecificacionProductoDetalle;
    public static javax.swing.JTextField txt_IdDetalleProducto;
    public static javax.swing.JTextField txt_IdItem1;
    public static javax.swing.JTextField txt_IdPresupuesto;
    public static javax.swing.JTextField txt_IdProveedor;
    public static javax.swing.JTextField txt_ImpuestoEntrada;
    private javax.swing.JTextField txt_ImpuestoTotal;
    public static javax.swing.JTextField txt_NombreProducto;
    public static javax.swing.JTextField txt_NombreProductoDetalle;
    private javax.swing.JTextField txt_PrecioContratado;
    private javax.swing.JTextField txt_Saldo;
    private javax.swing.JTextField txt_SaldoActual;
    private javax.swing.JTextField txt_Salidas;
    private javax.swing.JTextField txt_SubTotalAvance;
    private javax.swing.JTextField txt_SubTotalContratado;
    private javax.swing.JTextField txt_TotalEntrada;
    public static javax.swing.JTextField txt_UnidadItem;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_totalneto;
    // End of variables declaration//GEN-END:variables
}
